// Photographed merch, per brand — the manifest the brand manual reads.
//
// Generated by `scripts/merch-manifest.py` from what is actually on disk in
// `public/brand-merch`. The `_rejected-text` and `_offpalette` folders are
// deliberately NOT listed: those photos carry a misspelled wordmark or the wrong
// palette, and a brand manual that shows either is worse than one that shows a
// drawing. Nothing here is hand-edited — re-run the script after adding photos.
//
// `bg` is the median colour of each photo's outer 3px ring. The manual letterboxes
// rather than crops (these come back at anything from 0.56 to 2.24 aspect, and a
// square crop cuts wordmarks in half), so the tile is painted that colour and the
// letterbox band disappears into the photograph.

export type MerchPhoto = { i: string; w: number; h: number; bg: string };

const MERCH: Record<string, MerchPhoto[]> = {
  "ai-visibility": [
    { i: "jacket", w: 329, h: 306, bg: "#e7e5f3" },
    { i: "keyboard", w: 384, h: 306, bg: "#e7e5f3" },
    { i: "mousepad", w: 351, h: 252, bg: "#e7e5f3" },
  ],
  "aurelia": [
    { i: "apron", w: 291, h: 175, bg: "#272728" },
    { i: "cloth", w: 291, h: 175, bg: "#1f1f23" },
    { i: "coasters", w: 247, h: 175, bg: "#202123" },
    { i: "cups", w: 291, h: 175, bg: "#212326" },
    { i: "dosingring", w: 291, h: 175, bg: "#1f2123" },
    { i: "notebook", w: 291, h: 175, bg: "#1e1e20" },
    { i: "scoop", w: 291, h: 175, bg: "#1f2024" },
    { i: "tamper", w: 290, h: 175, bg: "#202326" },
  ],
  "barberia": [
    { i: "bowl", w: 302, h: 266, bg: "#242321" },
    { i: "comb", w: 301, h: 264, bg: "#232323" },
    { i: "envelope", w: 873, h: 289, bg: "#372e28" },
    { i: "stamp", w: 172, h: 167, bg: "#1e1713" },
    { i: "tote", w: 301, h: 202, bg: "#212224" },
    { i: "woodsign", w: 541, h: 258, bg: "#251d18" },
  ],
  "bella-calabria": [
    { i: "businesscard", w: 280, h: 225, bg: "#a98852" },
    { i: "cap", w: 361, h: 158, bg: "#f3efe3" },
    { i: "envelope", w: 470, h: 365, bg: "#628a58" },
    { i: "keyring", w: 316, h: 256, bg: "#f3efe3" },
    { i: "notebook", w: 335, h: 256, bg: "#f3f0e3" },
    { i: "passport", w: 358, h: 161, bg: "#f3efe3" },
    { i: "pin", w: 358, h: 193, bg: "#f3f0e3" },
    { i: "postcard", w: 345, h: 197, bg: "#a8852d" },
    { i: "tee", w: 361, h: 192, bg: "#f4f0e4" },
    { i: "tote", w: 379, h: 388, bg: "#f4f0e4" },
  ],
  "brado": [
    { i: "apron", w: 313, h: 454, bg: "#ffffff" },
    { i: "beanie", w: 297, h: 211, bg: "#ffffff" },
    { i: "envelope", w: 395, h: 235, bg: "#7f5b42" },
    { i: "growler", w: 295, h: 206, bg: "#ffffff" },
    { i: "hotsauce", w: 256, h: 454, bg: "#ffffff" },
    { i: "mug", w: 294, h: 211, bg: "#ffffff" },
    { i: "plates", w: 293, h: 211, bg: "#ffffff" },
    { i: "pouch", w: 410, h: 275, bg: "#8d7464" },
    { i: "spices", w: 293, h: 211, bg: "#ffffff" },
    { i: "tee", w: 300, h: 211, bg: "#ffffff" },
  ],
  "brasilena": [
    { i: "coasters", w: 97, h: 218, bg: "#f5f0df" },
    { i: "knife", w: 178, h: 227, bg: "#f5f0dd" },
    { i: "logo-a", w: 165, h: 229, bg: "#f5f0dd" },
    { i: "mug", w: 194, h: 229, bg: "#f5f0de" },
    { i: "opener", w: 178, h: 244, bg: "#f6f0e0" },
    { i: "signage", w: 540, h: 300, bg: "#f1ede4" },
    { i: "tote-pattern", w: 202, h: 227, bg: "#f5f0dd" },
    { i: "tote", w: 194, h: 244, bg: "#f5f0df" },
  ],
  "buss-travel": [
    { i: "box", w: 665, h: 490, bg: "#ccb89c" },
    { i: "businesscard", w: 395, h: 190, bg: "#d1ba9d" },
    { i: "cap", w: 262, h: 300, bg: "#e0e0de" },
    { i: "cup", w: 259, h: 300, bg: "#dfdfde" },
    { i: "envelope", w: 635, h: 238, bg: "#d4c1a5" },
    { i: "lanyard", w: 262, h: 312, bg: "#e0e0de" },
    { i: "letterhead", w: 765, h: 445, bg: "#d7c4ac" },
    { i: "luggagetag", w: 360, h: 215, bg: "#d5c4ac" },
    { i: "mug", w: 254, h: 300, bg: "#e0e0de" },
    { i: "pillow", w: 274, h: 312, bg: "#e1e1df" },
    { i: "pins", w: 259, h: 312, bg: "#e0e0de" },
    { i: "powerbank", w: 259, h: 312, bg: "#e0e0de" },
    { i: "suitcase", w: 274, h: 300, bg: "#e0e0de" },
    { i: "tee", w: 259, h: 300, bg: "#e0e0de" },
    { i: "tote", w: 254, h: 309, bg: "#e0e0de" },
  ],
  "fotografo": [
    { i: "businesscard-2", w: 251, h: 370, bg: "#2e2c2d" },
    { i: "businesscard", w: 252, h: 364, bg: "#2c2a2b" },
    { i: "cufflinks", w: 255, h: 248, bg: "#262627" },
    { i: "lenscap", w: 252, h: 235, bg: "#323031" },
    { i: "tote", w: 254, h: 239, bg: "#262526" },
    { i: "usb", w: 254, h: 235, bg: "#272627" },
  ],
  "gelateria": [
    { i: "cup", w: 1100, h: 1473, bg: "#744726" },
  ],
  "mirzz": [
    { i: "bottle", w: 254, h: 279, bg: "#efddd2" },
    { i: "earbudcase", w: 254, h: 233, bg: "#eddce8" },
    { i: "keyrings", w: 254, h: 233, bg: "#e0e2de" },
    { i: "powerbank", w: 254, h: 233, bg: "#f1ddd4" },
    { i: "straws", w: 254, h: 233, bg: "#d5e5f4" },
    { i: "tumbler", w: 254, h: 279, bg: "#d5e5f5" },
  ],
  "nordbageriet": [
    { i: "beanie", w: 263, h: 189, bg: "#121c19" },
    { i: "board", w: 265, h: 209, bg: "#121c19" },
    { i: "businesscard", w: 275, h: 185, bg: "#1f2c25" },
    { i: "cap", w: 245, h: 209, bg: "#121d19" },
    { i: "cardholder", w: 450, h: 230, bg: "#232f27" },
    { i: "cutters", w: 256, h: 189, bg: "#121c19" },
    { i: "letterhead", w: 510, h: 398, bg: "#24312a" },
    { i: "towel", w: 261, h: 189, bg: "#121c18" },
  ],
  "pizzeria-restaurant": [
    { i: "apron-2", w: 250, h: 321, bg: "#1c392a" },
    { i: "apron", w: 1100, h: 1473, bg: "#68472b" },
    { i: "bottle", w: 250, h: 321, bg: "#1b3829" },
    { i: "cup", w: 250, h: 321, bg: "#1c392a" },
    { i: "patch", w: 250, h: 329, bg: "#223f30" },
    { i: "tote", w: 250, h: 321, bg: "#1d3a2b" },
  ],
  "sushi": [
    { i: "apron", w: 305, h: 261, bg: "#f1ede1" },
    { i: "board", w: 305, h: 230, bg: "#f1ede1" },
    { i: "bottle", w: 327, h: 230, bg: "#f1ede1" },
    { i: "cap", w: 243, h: 264, bg: "#f1ede3" },
    { i: "envelope", w: 544, h: 135, bg: "#efebe2" },
    { i: "sake", w: 313, h: 264, bg: "#f1ede4" },
  ],
  "yoga": [
    { i: "block", w: 259, h: 249, bg: "#1d231c" },
    { i: "bottle", w: 261, h: 249, bg: "#1c231b" },
    { i: "businesscard", w: 430, h: 230, bg: "#9f9081" },
    { i: "cardholder", w: 510, h: 220, bg: "#9e8e7f" },
    { i: "charm", w: 235, h: 87, bg: "#6d645a" },
    { i: "cushion", w: 256, h: 249, bg: "#1c231c" },
    { i: "envelope", w: 420, h: 220, bg: "#907e6f" },
    { i: "eyepillow", w: 256, h: 228, bg: "#1c231b" },
    { i: "mat", w: 231, h: 249, bg: "#1c251d" },
    { i: "notebook", w: 261, h: 228, bg: "#1d221b" },
    { i: "pins", w: 259, h: 228, bg: "#1d231c" },
    { i: "tee", w: 239, h: 249, bg: "#1c231c" },
    { i: "tote", w: 231, h: 228, bg: "#1c231c" },
  ],
};

/** Every photo a brand has, in file order. Empty when it only has drawings. */
export function merchPhotos(slug: string): MerchPhoto[] {
  return MERCH[slug] ?? [];
}

export function merchSrc(slug: string, photo: MerchPhoto): string {
  return `/brand-merch/${slug}/${photo.i}.jpg`;
}

/**
 * The first photo whose filename is one of `names`, or null.
 *
 * The board's tiles are labelled by category ("packaging", "stationery"), so a
 * photo can only stand in for one when it is actually that kind of object. Left
 * to a positional pick, the stationery tile came back showing a beanie.
 */
export function merchPick(slug: string, names: readonly string[]): MerchPhoto | null {
  const all = MERCH[slug] ?? [];
  for (const name of names) {
    const hit = all.find((p) => p.i === name || p.i.startsWith(`${name}-`));
    if (hit) return hit;
  }
  return null;
}

/**
 * Up to `count` photos spread across the set rather than the first N, so the
 * cover, the mark page and the merch board never show the same three objects.
 * Never repeats: a brand with two photos gives back two, not four.
 */
export function merchSpread(slug: string, count: number, offset = 0): MerchPhoto[] {
  const all = MERCH[slug] ?? [];
  const take = Math.min(count, all.length);
  if (take === 0) return [];
  const step = all.length / take;
  const out: MerchPhoto[] = [];
  for (let i = 0; i < take; i += 1) {
    out.push(all[(offset + Math.floor(i * step)) % all.length]);
  }
  return out;
}
