// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use the DIRECT (session, :5432) URL — the pooled PgBouncer
    // (:6543) connection breaks DDL/prepared statements.
    url: process.env["DIRECT_URL"],
  },
});
