"""Write src/lib/brand-merch.ts from whatever photos are on disk.

The brand manual shows photographed merch where a brand has it and drawn merch
where it does not, so it needs to know — at build time, not at request time —
which photos exist. Scanning `public/brand-merch` here means the manual can never
reference a file that was rejected and deleted.

Only the top level of each brand folder is listed. `_rejected-text/` holds photos
whose wordmark came back misspelled and `_offpalette/` holds photos in the wrong
colours; both stay out of the manifest on purpose.

Each entry also carries the median colour of the photo's outer 3px ring. The
manual letterboxes instead of cropping (the generated sheets come back anywhere
between 0.56 and 2.24 aspect, and a square crop cuts wordmarks in half), and
painting the tile that colour hides the letterbox band.

Usage
    python scripts/merch-manifest.py
"""

import io
import os

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "public", "brand-merch")
OUT = os.path.join(ROOT, "src", "lib", "brand-merch.ts")

HEADER = '''// Photographed merch, per brand — the manifest the brand manual reads.
//
// Generated by `scripts/merch-manifest.py` from what is actually on disk in
// `public/brand-merch`. The `_rejected-text` and `_offpalette` folders are
// deliberately NOT listed: those photos carry a misspelled wordmark or the wrong
// palette, and a brand manual that shows either is worse than one that shows a
// drawing. Nothing here is hand-edited — re-run the script after adding photos.
//
// `bg` is the median colour of each photo's outer 3px ring. The manual letterboxes
// rather than crops (these come back at anything from 0.56 to 2.24 aspect, and a
// square crop cuts wordmarks in half), so the tile is painted that colour and the
// letterbox band disappears into the photograph.

export type MerchPhoto = { i: string; w: number; h: number; bg: string };

const MERCH: Record<string, MerchPhoto[]> = {
'''

FOOTER = '''};

/** Every photo a brand has, in file order. Empty when it only has drawings. */
export function merchPhotos(slug: string): MerchPhoto[] {
  return MERCH[slug] ?? [];
}

export function merchSrc(slug: string, photo: MerchPhoto): string {
  return `/brand-merch/${slug}/${photo.i}.jpg`;
}

/**
 * The first photo whose filename is one of `names`, or null.
 *
 * The board's tiles are labelled by category ("packaging", "stationery"), so a
 * photo can only stand in for one when it is actually that kind of object. Left
 * to a positional pick, the stationery tile came back showing a beanie.
 */
export function merchPick(slug: string, names: readonly string[]): MerchPhoto | null {
  const all = MERCH[slug] ?? [];
  for (const name of names) {
    const hit = all.find((p) => p.i === name || p.i.startsWith(`${name}-`));
    if (hit) return hit;
  }
  return null;
}

/**
 * Up to `count` photos spread across the set rather than the first N, so the
 * cover, the mark page and the merch board never show the same three objects.
 * Never repeats: a brand with two photos gives back two, not four.
 */
export function merchSpread(slug: string, count: number, offset = 0): MerchPhoto[] {
  const all = MERCH[slug] ?? [];
  const take = Math.min(count, all.length);
  if (take === 0) return [];
  const step = all.length / take;
  const out: MerchPhoto[] = [];
  for (let i = 0; i < take; i += 1) {
    out.push(all[(offset + Math.floor(i * step)) % all.length]);
  }
  return out;
}
'''


def edge_colour(im):
    a = np.asarray(im)
    ring = np.concatenate([
        a[:3].reshape(-1, 3), a[-3:].reshape(-1, 3),
        a[:, :3].reshape(-1, 3), a[:, -3:].reshape(-1, 3),
    ])
    r, g, b = np.median(ring, axis=0).astype(int)
    return "#%02x%02x%02x" % (r, g, b)


def main():
    rows = []
    for slug in sorted(os.listdir(SRC)):
        folder = os.path.join(SRC, slug)
        if not os.path.isdir(folder):
            continue
        items = []
        for f in sorted(x for x in os.listdir(folder) if x.endswith(".jpg")):
            im = Image.open(os.path.join(folder, f)).convert("RGB")
            items.append((os.path.splitext(f)[0], im.width, im.height, edge_colour(im)))
        if items:
            rows.append((slug, items))

    body = "".join(
        '  "%s": [\n%s  ],\n' % (
            slug,
            "".join('    { i: "%s", w: %d, h: %d, bg: "%s" },\n' % it for it in items),
        )
        for slug, items in rows
    )
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(HEADER + body + FOOTER)
    print("%d brands, %d photos -> %s"
          % (len(rows), sum(len(i) for _, i in rows), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
